
--[[
-- MIT License

Copyright (c) 2025 Ron Xavier

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
]]

-- Auto-generated by mk-nvim-colors on 2025-10-14T20:28:12-04:00

return {
  red = "#d32f2f",
  orange = "#d32f2f",
  green = "#388e3c",
  yellow = "#fbc02d", 
  blue = "#1976d2",
  magenta = "#7b1fa2",
  cyan = "#0097a7",
  black = "#000000",
  bright_red = "#ef5350",
  bright_orange = "#ef5350",
  bright_green = "#66bb6a",
  bright_yellow = "#ffeb3b",
  bright_blue = "#42a5f5",
  bright_magenta = "#ba68c8",
  bright_cyan = "#26c6da",
  white = "#26c6da",
  gutter_fg = "#999999",
  nontext = "#999999",
  
  bg = "#ffffff", --black
  fg         = "#000000", --white
  cursorline = "#1976d2", --light grey
  selection  = "#000000", --black
  linenr     = "#424242", --dark-gray
  comment    = "#999999", --grey

  keyword    = "#d32f2f", --
  Function   = "#388e3c", --
  string     = "#424242",
  constant   = "#424242",
  type       = "#1976d2",
  number     = "#7b1fa2",
  boolean    = "#1976d2",
  operator   = "#1976d2",
  variable   = "#1976d2",

  cursor     = "#000000",
  visual     = "#1976d2",
  search     = "#f5c2e7",
  statusline = "#1e293b",
  menu_bg    = "#1a2535",
  menu_sel   = "#3b4252",
  fold       = "#3e4a5a",
  split      = "#334155",

  diag_error = "#f38ba8",
  diag_warn  = "#fab387",
  diag_info  = "#89dceb",
  diag_hint  = "#b4befe",
}

