# Auto-generated by mk-nvim-colors on 2025-07-28T13:50:34-04:00
local M = {}

M.setup = function()
  vim.opt.termguicolors = true

  -- base groups
  vim.api.nvim_set_hl(0, 'Normal',        { fg = "#000000", bg = "#ffffff" })
  vim.api.nvim_set_hl(0, 'LineNr',        { fg = "#000000", bg = "#ffffff" })
  vim.api.nvim_set_hl(0, 'CursorLine',    { bg = "#ffffff" })
  vim.api.nvim_set_hl(0, 'CursorLineNr',  { fg = "#1976d2", bg = "#ffffff", bold = true })
  vim.api.nvim_set_hl(0, 'Visual',        { bg = "#26c6da" })
  vim.api.nvim_set_hl(0, 'StatusLine',    { fg = "#ffffff", bg = "#1976d2" })
  vim.api.nvim_set_hl(0, 'VertSplit',     { fg = "#999999" })
  vim.api.nvim_set_hl(0, 'Comment',       { fg = "#999999", italic = true })

  -- diagnostics (optional)
  vim.api.nvim_set_hl(0, 'DiagnosticError', { fg = "#d32f2f" })
  vim.api.nvim_set_hl(0, 'DiagnosticWarn',  { fg = "#fbc02d" })
  vim.api.nvim_set_hl(0, 'DiagnosticInfo',  { fg = "#1976d2" })
  vim.api.nvim_set_hl(0, 'DiagnosticHint',  { fg = "#0097a7" })
end

return M

