[general]
	live_config_reload = true
	import = ["~/.config/alacritty/colors.toml"]

[font]
	normal = { family = "mononoki", style = "Regular" }
	size = 16.0

[cursor]
	style = { shape = "Beam", blinking = "Off" }
	unfocused_hollow = false

[mouse]
	hide_when_typing = true

