-- ~/.config/nvim/init.lua

-- 1. Leader key early
vim.g.mapleader = " "

-- 2. Load color palette (generated by mk‑nvim‑colors)

-- 3. Core options
local opt = vim.opt
opt.number         = true   -- line numbers
opt.relativenumber = true
opt.cursorline     = false
opt.expandtab      = true
opt.shiftwidth     = 4
opt.tabstop        = 4
opt.clipboard      = "unnamedplus"
opt.termguicolors  = true
opt.signcolumn     = "yes"
vim.api.nvim_set_hl(0, "Normal", { bg = "none" })
vim.api.nvim_set_hl(0, "NormalFloat", { bg = "none" })
vim.api.nvim_set_hl(0, "NormalNC", { bg = "none" })

-- 4. Lazy‑load plugins
require("config.lazy")

