-- ~/.config/nvim/init.lua

-- 1. Leader key early
vim.g.mapleader = " "

-- 2. Load color palette (generated by mk‑nvim‑colors)
-- require("colors.generated").setup()

-- 3. Core options
local opt = vim.opt
opt.number         = true   -- line numbers
opt.relativenumber = true
opt.cursorline     = false
opt.expandtab      = true
opt.shiftwidth     = 4
opt.tabstop        = 4
opt.clipboard      = "unnamedplus"
opt.termguicolors  = true
opt.signcolumn     = "yes"

-- 4. Lazy‑load plugins
--require("plugins")

